version: "3"

tasks:
  default:
    desc: Runs the help task
    deps: [help]
    silent: True

  help:
    desc: Runs the list tasks
    cmds:
      - task --list
    silent: True

  build:
    desc: Build the app
    cmds:
    - GOFLAGS=-mod=mod go build -o rbkr main.go 

  run: 
    desc: Run the app
    cmds:
    - GOFLAGS=-mod=mod go run main.go

